### ISSUE TITLE
how to generate fsrnet lr img ?

### ISSUE THREAD

**Issue by nmber5** [cydiachen/FSRNET_pytorch#1]
how to generate lr img, can you share a detail steps in fsrnet?

**Comment by cydiachen** [comment]
I want to know whether you want to train your own model, or you want to try out the whole model to show the system performance?

**Comment by nmber5** [comment]
> I want to know whether you want to train your own model, or you want to try out the whole model to show the system performance?

i want to try out the whole model. when i trying to generate the lr img from celeba Hr img, i found the lr img i generated is different with the https://github.com/tyshiwo/FSRNet lr img given. then the performance of fsrnet is bad.
