### ISSUE TITLE
您好，上传的代码跑不起来，有些函数的参数没有说明，然后也没有传参，是不是传错版本了？

### ISSUE THREAD

**Issue by yuanlunxi** [cydiachen/FSRNET_pytorch#12]

**Comment by cydiachen** [comment]
你好，请问下可否上传一个有疑问的参数呢？因为我这里最近在修改自己的论文，您看一下哪里有报错，我帮你debug一下。等我论文完成了可能会重新整理一下代码

**Comment by yuanlunxi** [comment]
你好，感谢在百忙之中回复我的消息。我在跑代码的过程中遇到了几个小问题：
1：utils目录可能下面缺少了文件 ：image_pool，util；在跑代码的时候回提示缺少模块
2:  define_G这个函数的参数ngf，和which_model_netG没有传参也没有参数说明；
另外付两个疑问：train.py好像没有实现fsrgan的训练方式，提供的是fsrnet的方式，后面是否可以补充一下fsrgan的训练脚本呢？
4：数据流里面parsingmap这个数据是从在哪里呢？是百度网盘里的那个数据么？
谢谢啦

**Comment by yuanlunxi** [comment]
百度网盘下载速度太慢，数据集方便发一下邮箱吗？yuanlunxi@foxmail.com，谢谢。或者是不是实用helen数据集也是可以用这份代码的？

**Comment by cydiachen** [comment]
> 百度网盘下载速度太慢，数据集方便发一下邮箱吗？[yuanlunxi@foxmail.com](mailto:yuanlunxi@foxmail.com)，谢谢。或者是不是实用helen数据集也是可以用这份代码的？

是的 可以使用这份代码 可能就是dataloder部分需要改写一下。另外：采用 zllrunning/face-parsing.PyTorch(https://github.com/zllrunning/face-parsing.PyTorch) with pretrained model.也可以在任意人脸数据集生成parsing map

**Comment by cydiachen** [comment]
> 你好，感谢在百忙之中回复我的消息。我在跑代码的过程中遇到了几个小问题：
> 1：utils目录可能下面缺少了文件 ：image_pool，util；在跑代码的时候回提示缺少模块
> 2: define_G这个函数的参数ngf，和which_model_netG没有传参也没有参数说明；
> 另外付两个疑问：train.py好像没有实现fsrgan的训练方式，提供的是fsrnet的方式，后面是否可以补充一下fsrgan的训练脚本呢？
> 4：数据流里面parsingmap这个数据是从在哪里呢？是百度网盘里的那个数据么？
> 谢谢啦
util那一部分可能是我文件处理问题，哪一行注释即可。有空的话我会提供一下FSRGAN的代码 ，最近在忙着paper ddl，忙完了我把这个更新一下，感谢

**Comment by snowBrain** [comment]
> 你好，感谢在百忙之中回复我的消息。我在跑代码的过程中遇到了几个小问题：
> 1：utils目录可能下面缺少了文件 ：image_pool，util；在跑代码的时候回提示缺少模块
> 2: define_G这个函数的参数ngf，和which_model_netG没有传参也没有参数说明；
> 另外付两个疑问：train.py好像没有实现fsrgan的训练方式，提供的是fsrnet的方式，后面是否可以补充一下fsrgan的训练脚本呢？
> 4：数据流里面parsingmap这个数据是从在哪里呢？是百度网盘里的那个数据么？
> 谢谢啦

你好！  请问ngf和which_model_netG这个问题解决了吗？

**Comment by wytcsuch** [comment]
> > 你好，感谢在百忙之中回复我的消息。我在跑代码的过程中遇到了几个小问题：
> > 1：utils目录可能下面缺少了文件 ：image_pool，util；在跑代码的时候回提示缺少模块
> > 2: define_G这个函数的参数ngf，和which_model_netG没有传参也没有参数说明；
> > 另外付两个疑问：train.py好像没有实现fsrgan的训练方式，提供的是fsrnet的方式，后面是否可以补充一下fsrgan的训练脚本呢？
> > 4：数据流里面parsingmap这个数据是从在哪里呢？是百度网盘里的那个数据么？
> > 谢谢啦
> 
> 你好！ 请问ngf和which_model_netG这个问题解决了吗？

已经不需要这两个参数了 直接删掉可以跑的
