### ISSUE TITLE
Steps to follow to run this projects ?

### ISSUE THREAD

**Issue by JauB1981** [cydiachen/FSRNET_pytorch#8]
Can someone explain to me what are the steps to follow for executing this projects : first file to execute, second one ...?
I want to execute it under Google Colab.
Thanks.

**Comment by cydiachen** [comment]
TO be updated at the end of this month.

**Comment by JauB1981** [comment]
Thanks mister. and it will be better if you can provide us the differents files missed on the project like : sr_1_4_0model_epoch_160_iter_0.pth,  lr_no_noise.npy ,11_parsing_maps.npy ,gts.npy ,val_lr1.npy ,val_gts1.npy ...
Because without these files, the project can not be tested from our side :)
